"""Add likes table

Revision ID: 2df0dfa9e073
Revises: bdd612445d3e
Create Date: 2026-05-07 22:10:35.149816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df0dfa9e073'
down_revision = 'bdd612445d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('likeID', sa.Integer(), nullable=False),
    sa.Column('liker_id', sa.Integer(), nullable=False),
    sa.Column('liked_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['liked_id'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['liker_id'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('likeID'),
    sa.UniqueConstraint('liker_id', 'liked_id', name='unique_like_pair')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_liked_id'), ['liked_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_liker_id'), ['liker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_liker_id'))
        batch_op.drop_index(batch_op.f('ix_likes_liked_id'))

    op.drop_table('likes')
    # ### end Alembic commands ###
