"""empty message

Revision ID: 610a3a533e56
Revises: 
Create Date: 2026-04-19 20:11:18.371041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610a3a533e56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('interestID', sa.Integer(), nullable=False),
    sa.Column('interest_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('interestID'),
    sa.UniqueConstraint('interest_name')
    )
    op.create_table('location',
    sa.Column('locationID', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('locationID')
    )
    op.create_table('users',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('looking_for', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_visibility', sa.Boolean(), nullable=True),
    sa.Column('locationID', sa.Integer(), nullable=True),
    sa.Column('preferred_radius', sa.Integer(), nullable=True),
    sa.Column('profile_picture', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['locationID'], ['location.locationID'], ),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('favourites',
    sa.Column('favouriteID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('saved_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['saved_user_id'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('favouriteID')
    )
    op.create_table('matches',
    sa.Column('matchID', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=True),
    sa.Column('user2_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('mutual_match', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('matchID')
    )
    op.create_table('notifications',
    sa.Column('notificationID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('notificationID')
    )
    op.create_table('user_interests',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('interestID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interestID'], ['interests.interestID'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('userID', 'interestID')
    )
    op.create_table('messages',
    sa.Column('messageID', sa.Integer(), nullable=False),
    sa.Column('matchID', sa.Integer(), nullable=True),
    sa.Column('senderID', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['matchID'], ['matches.matchID'], ),
    sa.ForeignKeyConstraint(['senderID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('messageID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('user_interests')
    op.drop_table('notifications')
    op.drop_table('matches')
    op.drop_table('favourites')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('location')
    op.drop_table('interests')
    # ### end Alembic commands ###
