"""Add block and report models

Revision ID: c68c0f2619de
Revises: 610a3a533e56
Create Date: 2026-05-06 12:39:50.906628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68c0f2619de'
down_revision = '610a3a533e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('blockID', sa.Integer(), nullable=False),
    sa.Column('blockerID', sa.Integer(), nullable=False),
    sa.Column('blockedID', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blockedID'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['blockerID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('blockID')
    )
    op.create_table('reports',
    sa.Column('reportID', sa.Integer(), nullable=False),
    sa.Column('reporterID', sa.Integer(), nullable=False),
    sa.Column('reportedID', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reportedID'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['reporterID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('reportID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('blocks')
    # ### end Alembic commands ###
